apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
  namespace: nodejsapp-dev
  labels:
    app: nodejsapp
    costcenter: dvsaidevops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: nodejsapp:v1.0.0
        ports:
        - containerPort: 8080
---
