apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
  namespace: nodejsapp-pt
  labels:
    app: myapp
    costcenter: dvsaidevops
spec:
  type: ClusterIP
  selector:
    app: nodejsapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
