apiVersion: apps/v1
kind: Deployment
metadata:
  name: NodeJs-app
  namespace: NodeJs-app-uat
  labels:
    app: NodeJs-app
    costcenter: aidevops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: NodeJs-app
  template:
    metadata:
      labels:
        app: NodeJs-app
    spec:
      containers:
      - name: NodeJs-app
        image: NodeJs-app:v2.0.0
        ports:
        - containerPort: 8080
---
